[project]
name = "ec-sympo-scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.12.5",
    "pymupdf-layout>=1.26.6",
    "pymupdf4llm>=0.2.9",
    "returns>=0.26.0",
    "tqdm>=4.67.1",
]
